# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConstantUUID' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ConstantUUID
  pod 'SAMKeychain'

end
